name: CD

on:
  push:
    branches:
      - main

# permissions:
#   actions: read
#   contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # # This enables task distribution via Nx Cloud
      # # Run this command as early as possible, before dependencies are installed
      # # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
      #
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install setuptools on macOS
        if: matrix.os == 'macos-latest'
        run: python3 -m pip install setuptools --break-system-packages

      - name: Install dependencies
        run: npm ci

      # - name: Derive appropriate SHAs for base and head for `nx affected` commands
      #   uses: nrwl/nx-set-shas@v4

      - name: Build renderer
        run: npx nx run-many -t build

      - name: Build executable
        run: npx nx run spie:make

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os }}
          path: dist/executables

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download executables
        uses: actions/download-artifact@v4
        with:
          path: dist/executables
          merge-multiple: true

      - name: Run nx release
        run: npx nx release

      - name: Upload Assets to Release
        uses: csexton/release-asset-action@v3
        with:
          pattern: |
            'dist/executables/latest*.yml'
            'dist/executables/*.xz'
            'dist/executables/*.rpm'
            'dist/executables/*.zip'
            'dist/executables/*.dmg'
            'dist/executables/*.exe'
            'dist/executables/*.deb'
          github-token: ${{ secrets.GITHUB_TOKEN }}
